=== KlausEB/JavaDataFormat/src/main/resources/schema_gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="https://example.com/gem"
        xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://example.com/gem"
        version="1.0"
        elementFormDefault="qualified">
    <element name="gems">
        <complexType>
            <sequence>
                <element name="gem"
                         type="tns:Gem"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Gem">
        <sequence>
            <element name="name" type="string"/>
            <element name="preciousness" type="tns:Preciousness"/>
            <element name="origin" type="string"/>
            <element name="visual" type="tns:Visual"/>
        </sequence>
        <attribute name="value" type="positiveInteger" use="required"/>
    </complexType>
    <simpleType name="Preciousness">
        <restriction base="string">
            <enumeration value="PRECIOUS"/>
            <enumeration value="SEMIPRECIOUS"/>
        </restriction>
    </simpleType>
    <complexType name="Visual">
        <sequence>
            <element name="color" type="tns:Color"/>
            <element name="transparency" type="tns:Transparency"/>
            <element name="cuttingMethod" type="tns:CuttingMethod"/>
        </sequence>
    </complexType>
    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="RED"/>
            <enumeration value="GREEN"/>
            <enumeration value="BLUE"/>
            <enumeration value="WHITE"/>
        </restriction>
    </simpleType>
    <simpleType name="Transparency">
        <restriction base="positiveInteger">
            <pattern value="(\d{1,2})|(100)"/>
        </restriction>
    </simpleType>
    <simpleType name="CuttingMethod">
        <restriction base="string">
            <enumeration value="ROSE"/>
            <enumeration value="DIAMOND"/>
            <enumeration value="STEPWISE"/>
            <enumeration value="TABLE"/>
            <enumeration value="EMERALD"/>
            <enumeration value="ASHER"/>
            <enumeration value="WEDGES"/>
        </restriction>
    </simpleType>
</schema>

=== KlausEB/JavaDataFormat/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://example.com/gem"
      xsi:schemaLocation="https://example.com/gem schema_gems.xsd">
    <gem value="15">
        <name>Diamond</name>
        <preciousness>PRECIOUS</preciousness>
        <origin>Russia, Perm province</origin>
        <visual>
            <color>WHITE</color>
            <transparency>90</transparency>
            <cuttingMethod>DIAMOND</cuttingMethod>
        </visual>
    </gem>
    <gem value="25">
        <name>Emerald</name>
        <preciousness>PRECIOUS</preciousness>
        <origin>Colombia</origin>
        <visual>
            <color>GREEN</color>
            <transparency>60</transparency>
            <cuttingMethod>ROSE</cuttingMethod>
        </visual>
    </gem>
    <gem value="20">
        <name>Garnet</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <origin>Karelia</origin>
        <visual>
            <color>RED</color>
            <transparency>10</transparency>
            <cuttingMethod>ASHER</cuttingMethod>
        </visual>
    </gem>
</gems>
